# IMPORTING and loading data

In [46]:
import torch

In [47]:
x= torch.tensor([
    0,
    0.05,
    0.1,
    0.15,
    0.2,
    0.25,
    0.3,
    0.35,
    0.4,
    0.45,
    0.5,
    0.55,
    0.6,
    0.65,
    0.7,
    0.75,
    0.8,
    0.85,
    0.9,
    0.95,
    1.0,
])

In [48]:
y= torch.tensor( [
    0,
    0.1,
    0.2,
    0.3,
    0.4,
    0.5,
    0.6,
    0.7,
    0.8,
    0.9,
    1,
    0.9,
    0.8,
    0.7,
    0.6,
    0.5,
    0.4,
    0.3,
    0.2,
    0.1,
    0,
])

# Reshaping the data as batch

In [49]:
x=x.reshape(x.shape[0],1)

In [50]:
y=y.reshape(y.shape[0],1)

In [51]:
x

tensor([[0.0000],
        [0.0500],
        [0.1000],
        [0.1500],
        [0.2000],
        [0.2500],
        [0.3000],
        [0.3500],
        [0.4000],
        [0.4500],
        [0.5000],
        [0.5500],
        [0.6000],
        [0.6500],
        [0.7000],
        [0.7500],
        [0.8000],
        [0.8500],
        [0.9000],
        [0.9500],
        [1.0000]])

In [52]:
y

tensor([[0.0000],
        [0.1000],
        [0.2000],
        [0.3000],
        [0.4000],
        [0.5000],
        [0.6000],
        [0.7000],
        [0.8000],
        [0.9000],
        [1.0000],
        [0.9000],
        [0.8000],
        [0.7000],
        [0.6000],
        [0.5000],
        [0.4000],
        [0.3000],
        [0.2000],
        [0.1000],
        [0.0000]])

# For our nx1 data , we have to pass it to 2 neurons and then biases 
# so 1x2 weigts to get nx2 
# then 1x2 biases , a bias for each neuron 
# so nx2 + 1x2 = nx2

In [53]:
w1= torch.rand(1,2, requires_grad=True)
b1=torch.rand(1,2, requires_grad=True)

In [54]:
summation1=x.matmul(w1)

In [55]:
summation1

tensor([[0.0000, 0.0000],
        [0.0253, 0.0029],
        [0.0505, 0.0058],
        [0.0758, 0.0086],
        [0.1011, 0.0115],
        [0.1263, 0.0144],
        [0.1516, 0.0173],
        [0.1769, 0.0202],
        [0.2022, 0.0231],
        [0.2274, 0.0259],
        [0.2527, 0.0288],
        [0.2780, 0.0317],
        [0.3032, 0.0346],
        [0.3285, 0.0375],
        [0.3538, 0.0403],
        [0.3790, 0.0432],
        [0.4043, 0.0461],
        [0.4296, 0.0490],
        [0.4548, 0.0519],
        [0.4801, 0.0547],
        [0.5054, 0.0576]], grad_fn=<MmBackward0>)

In [56]:
output1= summation1 + b1

In [57]:
output1

tensor([[0.2460, 0.4251],
        [0.2713, 0.4280],
        [0.2965, 0.4309],
        [0.3218, 0.4338],
        [0.3471, 0.4367],
        [0.3723, 0.4395],
        [0.3976, 0.4424],
        [0.4229, 0.4453],
        [0.4482, 0.4482],
        [0.4734, 0.4511],
        [0.4987, 0.4540],
        [0.5240, 0.4568],
        [0.5492, 0.4597],
        [0.5745, 0.4626],
        [0.5998, 0.4655],
        [0.6250, 0.4684],
        [0.6503, 0.4712],
        [0.6756, 0.4741],
        [0.7008, 0.4770],
        [0.7261, 0.4799],
        [0.7514, 0.4828]], grad_fn=<AddBackward0>)

# Now we have data in the form nx2 ,  the output of 2 neurons , 
# Now to feed it into a single final neuron multiply it with a weights vector of 2x1 to get nx1 data output 
# from final neuron and a single bias 

In [58]:
w2= torch.rand(2,1, requires_grad=True)
b2=torch.rand(1,1, requires_grad=True)

In [59]:
summation2= output1.matmul(w2)

In [60]:
summation2

tensor([[0.2506],
        [0.2689],
        [0.2871],
        [0.3054],
        [0.3237],
        [0.3419],
        [0.3602],
        [0.3785],
        [0.3967],
        [0.4150],
        [0.4333],
        [0.4515],
        [0.4698],
        [0.4881],
        [0.5063],
        [0.5246],
        [0.5429],
        [0.5611],
        [0.5794],
        [0.5977],
        [0.6159]], grad_fn=<MmBackward0>)

In [61]:
output2=summation2 + b2

In [62]:
output2

tensor([[0.7045],
        [0.7228],
        [0.7411],
        [0.7593],
        [0.7776],
        [0.7959],
        [0.8141],
        [0.8324],
        [0.8507],
        [0.8690],
        [0.8872],
        [0.9055],
        [0.9238],
        [0.9420],
        [0.9603],
        [0.9786],
        [0.9968],
        [1.0151],
        [1.0334],
        [1.0516],
        [1.0699]], grad_fn=<AddBackward0>)

In [63]:
y

tensor([[0.0000],
        [0.1000],
        [0.2000],
        [0.3000],
        [0.4000],
        [0.5000],
        [0.6000],
        [0.7000],
        [0.8000],
        [0.9000],
        [1.0000],
        [0.9000],
        [0.8000],
        [0.7000],
        [0.6000],
        [0.5000],
        [0.4000],
        [0.3000],
        [0.2000],
        [0.1000],
        [0.0000]])

# Our mean squared error formula

In [64]:
loss= ((y- output2)**2).mean()

# Now backpropagate the whole graph with respect to the loss function

In [65]:
loss.backward()

# We have the gradients

In [66]:
w1.grad

tensor([[0.3356, 0.0876]])

In [67]:
w2.grad

tensor([[0.4438],
        [0.3770]])

In [68]:
b1.grad

tensor([[0.5771, 0.1506]])

In [69]:
b2.grad

tensor([[0.8221]])

#

# Lets Put it together

## Initialize the weights

In [70]:
w1= torch.rand(1,2, requires_grad=True)
b1=torch.rand(1,2, requires_grad=True)
w2= torch.rand(2,1, requires_grad=True)
b2=torch.rand(1,1, requires_grad=True)

## Forward Pass

In [71]:
def forward(x):
    summation1=x.matmul(w1)
    output1= summation1 + b1
    summation2= output1.matmul(w2)
    output2=summation2 + b2
    return output2

## Loss function

In [72]:
def loss(y,yPred):
    return ((y- yPred)**2).mean()

In [73]:
nIter=1000
learningRate=0.01

## For each of epoch, forward pass , calculate the loss , and then backward pass to calculate the gradients

## Then according to the gradients, update the weights, but weight updation is not the part of computational graph,
## so we do that with gradient detachment, otherwise it would get included in the gradient calculation
## Then finally we need to clear the gradient variables to stop it from accumulating

In [75]:
for epoch in range(nIter):
    # predict = forward pass
    yPred = forward(x)

    # loss
    l = loss(y, yPred)

    # calculate gradients = backward pass
    l.backward()

    # update weights
    #w.data = w.data - learning_rate * w.grad
    with torch.no_grad():
        w1 -= learningRate * w1.grad
    with torch.no_grad():    
        w2 -= learningRate *w2.grad
    with torch.no_grad():
        b1 -= learningRate * b1.grad
    with torch.no_grad():
        b2 -= learningRate *b2.grad

    # zero the gradients after updating
    w1.grad.zero_()
    w2.grad.zero_()
    b1.grad.zero_()
    b2.grad.zero_()

    print(f'epoch {epoch+1}:  loss = {l.item():.8f}')
print(w1,w2,b1,b2)

epoch 1:  loss = 0.09379084
epoch 2:  loss = 0.09378849
epoch 3:  loss = 0.09378615
epoch 4:  loss = 0.09378382
epoch 5:  loss = 0.09378148
epoch 6:  loss = 0.09377915
epoch 7:  loss = 0.09377683
epoch 8:  loss = 0.09377450
epoch 9:  loss = 0.09377220
epoch 10:  loss = 0.09376989
epoch 11:  loss = 0.09376757
epoch 12:  loss = 0.09376526
epoch 13:  loss = 0.09376297
epoch 14:  loss = 0.09376067
epoch 15:  loss = 0.09375838
epoch 16:  loss = 0.09375609
epoch 17:  loss = 0.09375378
epoch 18:  loss = 0.09375151
epoch 19:  loss = 0.09374923
epoch 20:  loss = 0.09374696
epoch 21:  loss = 0.09374470
epoch 22:  loss = 0.09374242
epoch 23:  loss = 0.09374017
epoch 24:  loss = 0.09373791
epoch 25:  loss = 0.09373564
epoch 26:  loss = 0.09373339
epoch 27:  loss = 0.09373115
epoch 28:  loss = 0.09372891
epoch 29:  loss = 0.09372666
epoch 30:  loss = 0.09372442
epoch 31:  loss = 0.09372219
epoch 32:  loss = 0.09371994
epoch 33:  loss = 0.09371774
epoch 34:  loss = 0.09371551
epoch 35:  loss = 0.093

In [76]:
w1

tensor([[0.4660, 0.7497]], requires_grad=True)