# Importing

In [1]:
import torch

## The container for data is tensor

### Initialize with appropriate shape

### The ones and zeros tensors

In [2]:
ones= torch.ones(5,4, dtype=torch.float)

In [3]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [4]:
zeros= torch.zeros(4,2, dtype=torch.float)

In [5]:
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

### To get the shape

In [6]:
zeros.shape

torch.Size([4, 2])

### Generate a random tensor

In [7]:
r= torch.rand(5,4, dtype= torch.float)

In [8]:
r

tensor([[0.2325, 0.5166, 0.6169, 0.0117],
        [0.0944, 0.6806, 0.7061, 0.0471],
        [0.3918, 0.7869, 0.0319, 0.1059],
        [0.7255, 0.1786, 0.5272, 0.4366],
        [0.7018, 0.9213, 0.9260, 0.5538]])

In [9]:
r2= torch.rand(1,dtype=torch.float)

In [10]:
r2

tensor([0.1594])

### Initialize tensor with your data or iterable

In [11]:
my= torch.tensor(1, dtype=torch.float)

In [12]:
my

tensor(1.)

In [13]:
my2= torch.tensor(range(5), dtype=torch.float)

In [14]:
my2

tensor([0., 1., 2., 3., 4.])

## Tensor Arithmetic

In [15]:
a1= torch.rand(5,4, dtype=torch.float)
a2= torch.rand(5,4, dtype =torch.float)
print(a1)
print('\n')
print(a2)

tensor([[0.3033, 0.8813, 0.4944, 0.2110],
        [0.2462, 0.1738, 0.4483, 0.0673],
        [0.1819, 0.2117, 0.1670, 0.7999],
        [0.4305, 0.8803, 0.4405, 0.9221],
        [0.2972, 0.3534, 0.9907, 0.4477]])


tensor([[0.1052, 0.0360, 0.3020, 0.2188],
        [0.9780, 0.4994, 0.5570, 0.2019],
        [0.9708, 0.2790, 0.2884, 0.4788],
        [0.4945, 0.7198, 0.1162, 0.4181],
        [0.1896, 0.1859, 0.8768, 0.2391]])


In [16]:
a1+a2

tensor([[0.4085, 0.9173, 0.7964, 0.4298],
        [1.2242, 0.6732, 1.0053, 0.2692],
        [1.1527, 0.4908, 0.4555, 1.2787],
        [0.9250, 1.6002, 0.5567, 1.3402],
        [0.4868, 0.5393, 1.8675, 0.6868]])

In [17]:
a1.add(a2)

tensor([[0.4085, 0.9173, 0.7964, 0.4298],
        [1.2242, 0.6732, 1.0053, 0.2692],
        [1.1527, 0.4908, 0.4555, 1.2787],
        [0.9250, 1.6002, 0.5567, 1.3402],
        [0.4868, 0.5393, 1.8675, 0.6868]])

### Inplace Operation

In [18]:
a1.add_(a2)

tensor([[0.4085, 0.9173, 0.7964, 0.4298],
        [1.2242, 0.6732, 1.0053, 0.2692],
        [1.1527, 0.4908, 0.4555, 1.2787],
        [0.9250, 1.6002, 0.5567, 1.3402],
        [0.4868, 0.5393, 1.8675, 0.6868]])

In [19]:
a1

tensor([[0.4085, 0.9173, 0.7964, 0.4298],
        [1.2242, 0.6732, 1.0053, 0.2692],
        [1.1527, 0.4908, 0.4555, 1.2787],
        [0.9250, 1.6002, 0.5567, 1.3402],
        [0.4868, 0.5393, 1.8675, 0.6868]])

In [20]:
a1.subtract(a2)

tensor([[0.3033, 0.8813, 0.4944, 0.2110],
        [0.2462, 0.1738, 0.4483, 0.0673],
        [0.1819, 0.2117, 0.1670, 0.7999],
        [0.4305, 0.8803, 0.4405, 0.9221],
        [0.2972, 0.3534, 0.9907, 0.4477]])

In [21]:
a1.mul(a2)

tensor([[0.0430, 0.0330, 0.2405, 0.0941],
        [1.1972, 0.3362, 0.5599, 0.0544],
        [1.1191, 0.1370, 0.1314, 0.6123],
        [0.4574, 1.1519, 0.0647, 0.5603],
        [0.0923, 0.1003, 1.6375, 0.1642]])

In [22]:
a1.matmul(a2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (5x4 and 5x4)

### View as another shape

In [31]:
a2 = a2.view(4,5)

In [32]:
a2

tensor([[0.1052, 0.0360, 0.3020, 0.2188, 0.9780],
        [0.4994, 0.5570, 0.2019, 0.9708, 0.2790],
        [0.2884, 0.4788, 0.4945, 0.7198, 0.1162],
        [0.4181, 0.1896, 0.1859, 0.8768, 0.2391]])

In [33]:
a1

tensor([[0.4085, 0.9173, 0.7964, 0.4298],
        [1.2242, 0.6732, 1.0053, 0.2692],
        [1.1527, 0.4908, 0.4555, 1.2787],
        [0.9250, 1.6002, 0.5567, 1.3402],
        [0.4868, 0.5393, 1.8675, 0.6868]])

In [34]:
a1.matmul(a2)

tensor([[0.9104, 0.9884, 0.7823, 1.9300, 0.8508],
        [0.8674, 0.9514, 1.0528, 1.8811, 1.5663],
        [1.0323, 0.7754, 0.9102, 2.1778, 1.6230],
        [1.6172, 1.4452, 1.1270, 3.3318, 1.7363],
        [1.1463, 1.3423, 1.3071, 2.5766, 1.0079]])

### View inferr

In [35]:
a3 = torch.rand(5,4)

In [36]:
a3.view(10,-1)

tensor([[0.3086, 0.7213],
        [0.5903, 0.0177],
        [0.8387, 0.4876],
        [0.7984, 0.5457],
        [0.4238, 0.1236],
        [0.2420, 0.7795],
        [0.1009, 0.7290],
        [0.3650, 0.9063],
        [0.3241, 0.4764],
        [0.8160, 0.0279]])

In [37]:
a3.view(10,-1).shape

torch.Size([10, 2])

#

## Scalars Operations

In [38]:
torch.ones(5,4)+7

tensor([[8., 8., 8., 8.],
        [8., 8., 8., 8.],
        [8., 8., 8., 8.],
        [8., 8., 8., 8.],
        [8., 8., 8., 8.]])

In [39]:
torch.tensor([2,2,2]) **2

tensor([4, 4, 4])

## Other Operations

In [40]:
newT= torch.rand(5,4)

In [41]:
newT

tensor([[0.1828, 0.0913, 0.4719, 0.2972],
        [0.5415, 0.8798, 0.7179, 0.9393],
        [0.2551, 0.9267, 0.5981, 0.9966],
        [0.3189, 0.1051, 0.0703, 0.3034],
        [0.3813, 0.4584, 0.2483, 0.4686]])

In [42]:
print(newT.min())
print(newT.max())
print(newT.mean())
print(torch.sigmoid(newT))
print(torch.sin(newT))

tensor(0.0703)
tensor(0.9966)
tensor(0.4626)
tensor([[0.5456, 0.5228, 0.6158, 0.5738],
        [0.6322, 0.7068, 0.6721, 0.7189],
        [0.5634, 0.7164, 0.6452, 0.7304],
        [0.5791, 0.5263, 0.5176, 0.5753],
        [0.5942, 0.6126, 0.5618, 0.6150]])
tensor([[0.1817, 0.0911, 0.4546, 0.2929],
        [0.5155, 0.7706, 0.6578, 0.8071],
        [0.2523, 0.7996, 0.5631, 0.8396],
        [0.3135, 0.1049, 0.0702, 0.2987],
        [0.3722, 0.4425, 0.2457, 0.4516]])


## Deep Copy

In [43]:
c= torch.rand(1,2, dtype=torch.float)

In [44]:
c

tensor([[0.8104, 0.3171]])

In [45]:
cc=c

In [46]:
cc

tensor([[0.8104, 0.3171]])

In [47]:
c[0,1]=2

In [48]:
c

tensor([[0.8104, 2.0000]])

In [49]:
cc

tensor([[0.8104, 2.0000]])

In [50]:
cc= c.clone()

In [51]:
cc

tensor([[0.8104, 2.0000]])

In [52]:
c[0,0]=1

In [53]:
c

tensor([[1., 2.]])

In [55]:
cc

tensor([[0.8104, 2.0000]])